### ISSUE TITLE
Broken on Silverstripe 3.5.4

### ISSUE THREAD

**Issue by MattyBalaam** [restruct/silverstripe-svg-images#2]
[User Warning] DataObject::__construct passed The value 'assets/Uploads/_resampled/ScaleWidthWzEyMDBd/intro-graphicx2.png'. It's supposed to be passed an array, taken straight from the database. Perhaps you should use DataList::create()->First(); instead?

**Comment by ec8or** [comment]
Did you manage to fix this?

**Comment by MattyBalaam** [comment]
I've not had any time to investigate, and just rolled back the Silverstripe version for now.

**Comment by micschk** [comment]
Hope this is fixed for the short term. Currently a bit busy, might take a while before I can take a proper look at this. Do you guys need a tag release for the fix now or can this wait until after?
