### ISSUE TITLE
Unable to uninstall module

### ISSUE THREAD

**Issue by AnonymousWebHunter** [restruct/silverstripe-svg-images#4]
You don't need any module to use svg's in Silverstripe, at least version >= 3, and also you can't remove this module, after deleting and trying dev/build?flush it will return the following error [User Error] Uncaught ReflectionException: Class SVGImage does not exist.

Something it's very wrong here.

**Comment by AnonymousWebHunter** [comment]
No more need, it was most likely caused by the yml:


```
Injector:
  Image:
    class: SVGImage
```

**Comment by straathof** [comment]
Thanks.
