### ISSUE TITLE
2: Clean up merged downstream PR in master/main

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-svg-images#9]
This was still on SS3, turns out there were quite a few forks already updated to SS4. 
I've selected the two most most active ones and created a PR from them back to this module. 
One has been merged to main/master and one to fractaslabs-edits. 

The one merged into main changes some stuff (module name, namespaces etc) to sunnysideup --> this needs to be changed to \Restruct\Silverstripe\SVG*. Further we should to go through the code to change any other references & clean up other stuff (if needed).

**Comment by patjnr** [comment]
Clean up done and merge completed.
